name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build and deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install parcel
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: 
            global add parcel-bundler
      - name: Build and deploy
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: 
            deploy
